create database customer_db;
use customer_db;
select * from customer Limit 5;
DESCRIBE customer;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- yeh vo customers h jinhone discount toh apply kiya h but jo avg purchase amount h usse jyada money(purchase amount) spent kiya h 
select customer_id,purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,
round(avg(review_rating),2) as avg_review_rating
from customer
group by item_purchased 
order by avg_review_rating desc
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
round(avg(purchase_amount),2) as avg_purchase_amount
from customer 
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and 
-- total revenue between subscribers and non-subscribers.
select  
subscription_status,
count(customer_id),
round(avg(purchase_amount),2) as avg_purchase_amount,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_purchase_amount,total_revenue desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*)*100,2) as percentage
from customer
group by item_purchased
order by percentage
limit 5;



-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
WITH customer_type AS (
   SELECT customer_id,
          previous_purchases,
          CASE
             WHEN previous_purchases = 1 THEN 'New'
             WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
             ELSE 'Loyal'
          END AS customer_segment
   FROM customer
)
SELECT customer_segment, COUNT(*) AS no_customer_count 
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT *
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

